## set echo set
create header, and fill the file after shuffle
``` 
     head -1 usa_00002.csv | awk -F ',' 'BEGIN{OFS=",";} {print $7,$44,$22}' > e.csv
     tail -n+2  usa_00002.csv | gshuf | awk -F ',' 'BEGIN{OFS=",";} {print $7,$44,$22}' >> e.csv
 ```       

In [10]:
import pandas as pd

import matplotlib
import matplotlib.pyplot as plt

#from matplotlib.pyplot import figure

print("matplotlib version: {}".format(matplotlib.__version__))
import mglearn
print("mglearn version: {}".format(mglearn.__version__))

#read the data file
path = './e.csv'
%time df = pd.read_csv(path)

states = pd.read_csv('./FIPS.csv')

matplotlib version: 2.2.2
mglearn version: 0.1.6
CPU times: user 1.08 s, sys: 185 ms, total: 1.27 s
Wall time: 1.28 s


In [11]:
states

stname   STATEFIP  stusps
0                Alabama          1      AL
1                 Alaska          2      AK
2                Arizona          4      AZ
3               Arkansas          5      AR
4             California          6      CA
5               Colorado          8      CO
6            Connecticut          9      CT
7               Delaware         10      DE
8   District of Columbia         11      DC
9                Florida         12      FL
10               Georgia         13      GA
11                Hawaii         15      HI
12                 Idaho         16      ID
13              Illinois         17      IL
14               Indiana         18      IN
15                  Iowa         19      IA
16                Kansas         20      KS
17              Kentucky         21      KY
18             Louisiana         22      LA
19                 Maine         23      ME
20              Maryland         24      MD
21         Massachusetts         25      MA
22              Michigan         26      MI
23             Minnesota         27      MN
24           Mississippi         28      MS
25              Missouri         29      MO
26               Montana         30      MT
27              Nebraska         31      NE
28                Nevada         32      NV
29         New Hampshire         33      NH
30            New Jersey         34      NJ
31            New Mexico         35      NM
32              New York         36      NY
33        North Carolina         37      NC
34          North Dakota         38      ND
35                  Ohio         39      OH
36              Oklahoma         40      OK
37                Oregon         41      OR
38          Pennsylvania         42      PA
39          Rhode Island         44      RI
40        South Carolina         45      SC
41          South Dakota         46      SD
42             Tennessee         47      TN
43                 Texas         48      TX
44                  Utah         49      UT
45               Vermont         50      VT
46              Virginia         51      VA
47            Washington         53      WA
48         West Virginia         54      WV
49             Wisconsin         55      WI
50               Wyoming         56      WY

In [12]:
# Shows averages per state
df = df[(df.INCTOT < 9999999) & (df.INCTOT !=0) ]

avgbystate = df.groupby(df.STATEFIP).mean()
avgbystate





INCTOT   FAMSIZE
STATEFIP                        
1         37737.017404  2.496513
2         39315.688723  3.231188
4         42130.305618  2.678925
5         34966.792488  2.524678
6         51546.729524  2.956305
8         49514.088319  2.564672
9         59812.380191  2.580051
10        47340.526122  2.576889
11        70425.451973  2.066987
12        43500.619911  2.513676
13        43190.745697  2.634462
15        46826.376305  3.260224
16        36939.567618  2.725260
17        46755.600571  2.664027
18        38016.326697  2.563161
19        38721.841928  2.485693
20        40021.999905  2.525196
21        38556.555176  2.522895
22        39223.085161  2.510838
23        38037.054581  2.391093
24        56440.602280  2.716746
25        54268.010825  2.559891
26        39899.977763  2.566412
27        44929.018812  2.568107
28        34650.941599  2.587279
29        38960.062801  2.539889
30        38465.552849  2.496791
31        39862.911430  2.529875
32        43112.575469  2.662268
33        47417.232420  2.509366
34        57959.584591  2.816725
35        36974.820162  2.669136
36        50292.751832  2.728851
37        41527.478002  2.511403
38        44733.556437  2.455374
39        40161.624814  2.521839
40        36639.257786  2.584346
41        42905.035810  2.494373
42        41709.249865  2.565998
44        45848.193840  2.452622
45        39501.028662  2.471393
46        38774.598371  2.555138
47        39480.584000  2.543377
48        45895.029536  2.790463
49        42442.130611  3.156672
50        40704.761142  2.443706
51        52780.180785  2.606993
53        49125.314985  2.586518
54        35195.532827  2.425958
55        40382.791806  2.536186
56        40303.748773  2.582379

In [22]:
#result = pd.merge(avgbystate,states, on='df.STATEFIP=states.STATEFIP', how='left')
result = avgbystate.join(states, how='left')
#result = result.stname,result.FAMSIZE,result.INCTOT
r = result.round(2)
#r3 = r2.drop(columns=['stname'])
#del r2['stname']
#del r2['INCTOT']
#r2.dtypes
#['INCTOT', 'FAMSIZE', 'stname', ' STATEFIP', ' stusps']
r =r[['stname', 'INCTOT','FAMSIZE']]
r

stname    INCTOT  FAMSIZE
STATEFIP                                         
1                       Alaska  37737.02     2.50
2                      Arizona  39315.69     3.23
4                   California  42130.31     2.68
5                     Colorado  34966.79     2.52
6                  Connecticut  51546.73     2.96
8         District of Columbia  49514.09     2.56
9                      Florida  59812.38     2.58
10                     Georgia  47340.53     2.58
11                      Hawaii  70425.45     2.07
12                       Idaho  43500.62     2.51
13                    Illinois  43190.75     2.63
15                        Iowa  46826.38     3.26
16                      Kansas  36939.57     2.73
17                    Kentucky  46755.60     2.66
18                   Louisiana  38016.33     2.56
19                       Maine  38721.84     2.49
20                    Maryland  40022.00     2.53
21               Massachusetts  38556.56     2.52
22                    Michigan  39223.09     2.51
23                   Minnesota  38037.05     2.39
24                 Mississippi  56440.60     2.72
25                    Missouri  54268.01     2.56
26                     Montana  39899.98     2.57
27                    Nebraska  44929.02     2.57
28                      Nevada  34650.94     2.59
29               New Hampshire  38960.06     2.54
30                  New Jersey  38465.55     2.50
31                  New Mexico  39862.91     2.53
32                    New York  43112.58     2.66
33              North Carolina  47417.23     2.51
34                North Dakota  57959.58     2.82
35                        Ohio  36974.82     2.67
36                    Oklahoma  50292.75     2.73
37                      Oregon  41527.48     2.51
38                Pennsylvania  44733.56     2.46
39                Rhode Island  40161.62     2.52
40              South Carolina  36639.26     2.58
41                South Dakota  42905.04     2.49
42                   Tennessee  41709.25     2.57
44                        Utah  45848.19     2.45
45                     Vermont  39501.03     2.47
46                    Virginia  38774.60     2.56
47                  Washington  39480.58     2.54
48               West Virginia  45895.03     2.79
49                   Wisconsin  42442.13     3.16
50                     Wyoming  40704.76     2.44
51                         NaN  52780.18     2.61
53                         NaN  49125.31     2.59
54                         NaN  35195.53     2.43
55                         NaN  40382.79     2.54
56                         NaN  40303.75     2.58

In [23]:
#reduce the dataframe to just the state and family size
df2 = df[['STATEFIP','FAMSIZE']]
a2 = df2.values #convert Data Frames to an Array 
a2.size
df3 = df[['INCTOT','FAMSIZE']]
a3 = df3.values


In [24]:
import numpy as np
from sklearn.cluster import KMeans



state_famzie_kmeans = KMeans(n_clusters=3)
state_famzie_kmeans.fit(a2)

income_famsize_kmeans =  KMeans(n_clusters=3)
income_famsize_kmeans.fit(a3)


KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [25]:
print ("cluser membership:\n{}".format(state_famzie_kmeans.labels_))

cluser membership:
[0 1 1 ... 1 1 2]


In [26]:
print(state_famzie_kmeans.predict(a2))
print(state_famzie_kmeans.predict(a3))

[0 1 1 ... 1 1 2]
[1 1 1 ... 1 1 1]


In [27]:
mglearn.discrete_scatter(a2[:,0],a2[:,], state_famzie_kmeans.labels_,markers='o')
mglearn.discrete_scatter(
    state_famzie_kmeans.cluster_centers_[:, 0], state_famzie_kmeans.cluster_centers_[:, 1], [0, 1, 2],
    markers='^', markeredgewidth=2)

In [28]:
plt.scatter(df2.STATEFIP,df2.FAMSIZE, s=1)

In [29]:
mglearn.discrete_scatter(a3[:,0],a3[:,], income_famsize_kmeans.labels_,markers='o')
mglearn.discrete_scatter(
    income_famsize_kmeans.cluster_centers_[:, 0], income_famsize_kmeans.cluster_centers_[:, 1], [0, 1, 2],
    markers='^', markeredgewidth=2)

In [21]:
plt.scatter(df2.STATEFIP,df2.FAMSIZE, s=1)
